
const mobileDevices = [
    "Apple iPhone 11",
    "Apple iPhone 11 Pro",
    "Apple iPhone 11 Pro Max",
    "Apple iPhone 12",
    "Apple iPhone 12 Mini",
    "Apple iPhone 12 Pro",
    "Apple iPhone 12 Pro Max",
    "Apple iPhone 13",
    "Apple iPhone 13 Mini",
    "Apple iPhone 13 Pro",
    "Apple iPhone 13 Pro Max",
    "Apple iPhone 14",
    "Apple iPhone 14 Plus",
    "Apple iPhone 14 Pro",
    "Apple iPhone 14 Pro Max",
    "Apple iPhone 15",
    "Apple iPhone 15 Plus",
    "Apple iPhone 15 Pro",
    "Apple iPhone 15 Pro Max",
    "Apple iPhone 16",
    "Apple iPhone 16 Plus",
    "Apple iPhone 16 Pro",
    "Apple iPhone 16 Pro Max",
    "Apple iPhone 16e",
    "Apple iPhone 6",
    "Apple iPhone 6 Plus",
    "Apple iPhone 6S",
    "Apple iPhone 6S Plus",
    "Apple iPhone 7",
    "Apple iPhone 7 Plus",
    "Apple iPhone 8",
    "Apple iPhone 8 Plus",
    "Apple iPhone SE 1st Generation",
    "Apple iPhone SE 2020",
    "Apple iPhone SE 2022",
    "Apple iPhone X",
    "Apple iPhone XR",
    "Apple iPhone XS",
    "Apple iPhone XS Max",
    "CMF by Nothing Phone 1",
    "Google Pixel 6a",
    "Google Pixel 7",
    "Google Pixel 7 Pro",
    "Google Pixel 7a",
    "Google Pixel 8",
    "Google Pixel 8 Pro",
    "Google Pixel 8a",
    "Google Pixel 9",
    "Google Pixel 9 Pro",
    "Google Pixel 9 Pro Fold",
    "Google Pixel 9 Pro XL",
    "Honor 10",
    "Honor 20",
    "Honor 200 5G",
    "Honor 200 Lite 5G",
    "Honor 200 Pro 5G",
    "Honor 20i",
    "Honor 7A",
    "Honor 7X",
    "Honor 8C",
    "Honor 8X",
    "Honor 9 Lite",
    "Honor 90",
    "Honor 9A",
    "Honor 9N",
    "Honor 9x Pro",
    "Honor Play",
    "Infinix GT 10 Pro",
    "Infinix GT 20 Pro",
    "Infinix Hot 10",
    "Infinix Hot 10 Play",
    "Infinix Hot 10s",
    "Infinix Hot 11",
    "Infinix Hot 11 2022",
    "Infinix Hot 11S",
    "Infinix Hot 12",
    "Infinix HOT 12 Play",
    "Infinix Hot 12 Pro",
    "Infinix Hot 20 5G",
    "Infinix Hot 20 Play",
    "Infinix Hot 30 5G",
    "Infinix Hot 30i",
    "Infinix Hot 40i",
    "Infinix Hot 50 5G",
    "Infinix Hot 7 Pro",
    "Infinix Hot 8",
    "Infinix Hot 9",
    "Infinix Hot 9 Pro",
    "Infinix Note 10",
    "Infinix Note 10 Pro",
    "Infinix Note 11",
    "Infinix Note 11s",
    "Infinix Note 11s Free Fire Edition",
    "Infinix Note 12",
    "Infinix Note 12 5G",
    "Infinix Note 12 Pro 4G",
    "Infinix Note 12 Pro 5G",
    "Infinix Note 12 Turbo",
    "Infinix Note 12i",
    "Infinix Note 30 5G",
    "Infinix Note 40 5G",
    "Infinix Note 40 Pro 5G",
    "Infinix Note 40 Pro Plus 5G",
    "Infinix Note 40X 5G",
    "Infinix Note 7",
    "Infinix S5",
    "Infinix S5 Pro",
    "Infinix Smart 4 Plus",
    "Infinix Smart 5",
    "Infinix Smart 6",
    "Infinix Smart 6 HD",
    "Infinix Smart 6 Plus",
    "Infinix Smart 7",
    "Infinix Smart 7 HD",
    "Infinix Smart 8",
    "Infinix Smart 8 HD",
    "Infinix Smart HD 2021",
    "Infinix Zero 20",
    "Infinix Zero 40 5G",
    "Infinix Zero 5 Pro",
    "Infinix Zero 5G",
    "Infinix Zero 5G 2023",
    "Infinix Zero 5G 2023 Turbo",
    "Infinix Zero 8i",
    "Infinix Zero Flip 5G",
    "Infinix Zero Ultra",
    "iQOO 11 5G",
    "iQOO 12 5G",
    "iQOO 13 5G",
    "iQOO 3",
    "iQOO 3 5G",
    "iQOO 7 5G",
    "iQOO 7 Legend 5G",
    "iQOO 9 5G",
    "iQOO 9 Pro 5G",
    "iQOO 9 SE 5G",
    "iQOO 9T 5G",
    "iQOO Neo 6 5G",
    "iQOO Neo 7 5G",
    "iQOO Neo 7 Pro 5G",
    "iQOO Neo 9 Pro 5G",
    "iQOO Z3 5G",
    "iQOO Z5 5G",
    "iQOO Z6",
    "iQOO Z6 5G",
    "iQOO Z6 Lite 5G",
    "iQOO Z6 Pro 5G",
    "iQOO Z7 5G",
    "iQOO Z7 Pro 5G",
    "iQOO Z7s 5G",
    "iQOO Z9 5G",
    "iQOO Z9 Lite 5G",
    "iQOO Z9s 5G",
    "iQOO Z9s Pro 5G",
    "iQOO Z9x 5G",
    "Lenovo K10 Note",
    "Lenovo K10 Plus",
    "Lenovo Z6 Pro",
    "Motorola Moto E13",
    "Motorola Moto e22s",
    "Motorola Moto e32",
    "Motorola Moto e32s",
    "Motorola Moto E40",
    "Motorola Moto E6s",
    "Motorola Moto E7 Plus",
    "Motorola Moto E7 Power",
    "Motorola Moto Edge 20",
    "Motorola Moto Edge 20 Fusion",
    "Motorola Moto Edge 20 Pro",
    "Motorola Moto Edge 30",
    "Motorola Moto Edge 30 Fusion",
    "Motorola Moto Edge 30 Pro",
    "Motorola Moto Edge 30 Ultra",
    "Motorola Moto Edge 40",
    "Motorola Moto Edge 40 Neo",
    "Motorola Moto Edge 50",
    "Motorola Moto Edge 50 Fusion",
    "Motorola Moto Edge 50 Neo",
    "Motorola Moto Edge 50 Pro",
    "Motorola Moto Edge 50 Ultra",
    "Motorola Moto Edge Plus",
    "Motorola Moto G 5G",
    "Motorola Moto G04",
    "Motorola Moto G04s",
    "Motorola Moto G05",
    "Motorola Moto G10 Power",
    "Motorola Moto G13",
    "Motorola Moto G14",
    "Motorola Moto G22",
    "Motorola Moto G24 Power",
    "Motorola Moto G30",
    "Motorola Moto G31",
    "Motorola Moto G32",
    "Motorola Moto G34 5G",
    "Motorola Moto G35 5G",
    "Motorola Moto G40 Fusion",
    "Motorola Moto G42",
    "Motorola Moto G45 5G",
    "Motorola Moto G51 5G",
    "Motorola Moto G52",
    "Motorola Moto G54 5G",
    "Motorola Moto G6",
    "Motorola Moto G6 Plus",
    "Motorola Moto G60",
    "Motorola Moto G62 5G",
    "Motorola Moto G64 5G",
    "Motorola Moto G7",
    "Motorola Moto G7 Power",
    "Motorola Moto G71 5G",
    "Motorola Moto G72",
    "Motorola Moto G73 5G",
    "Motorola Moto G8 Plus",
    "Motorola Moto G8 Power Lite",
    "Motorola Moto G82 5G",
    "Motorola Moto G84 5G",
    "Motorola Moto G85 5G",
    "Motorola Moto G9",
    "Motorola Moto G9 Power",
    "Motorola Moto One",
    "Motorola Moto Razr",
    "Motorola Moto Razr 40 Ultra",
    "Motorola Moto Razr 50",
    "Motorola Moto Razr 50 Ultra",
    "Motorola Moto Razr 5G",
    "Motorola Moto Z2 Force",
    "Motorola One Action",
    "Motorola One Fusion Plus",
    "Motorola One Macro",
    "Motorola One Power",
    "Motorola One Vision",
    "Nokia 2.2",
    "Nokia 2.4",
    "Nokia 3.2",
    "Nokia 3.4",
    "Nokia 4.2",
    "Nokia 5.1 Plus",
    "Nokia 5.3",
    "Nokia 5.4",
    "Nokia 6.1 Plus",
    "Nokia 6.2",
    "Nokia 7 Plus",
    "Nokia 7.1",
    "Nokia 7.2",
    "Nokia 8 Sirocco",
    "Nokia 8.1",
    "Nokia C01 Plus",
    "Nokia C12",
    "Nokia C12 Pro",
    "Nokia C20 Plus",
    "Nokia C21 Plus",
    "Nokia C22",
    "Nokia C30",
    "Nokia C31",
    "Nokia C32",
    "Nokia G10",
    "Nokia G11 Plus",
    "Nokia G20",
    "Nokia G21",
    "Nokia G42 5G",
    "Nokia G60 5G",
    "Nokia X30 5G",
    "Nokia XR20",
    "Nothing Phone 1",
    "Nothing Phone 2",
    "Nothing Phone 2a 5G",
    "Nothing Phone 2a Plus",
    "Nothing Phone 3a",
    "Nothing Phone 3a Pro",
    "OnePlus 10 Pro 5G",
    "OnePlus 10R 5G",
    "OnePlus 10T 5G",
    "OnePlus 11 5G",
    "Oneplus 11 5G Marble Edition",
    "OnePlus 11R 5G",
    "OnePlus 12",
    "OnePlus 12R",
    "OnePlus 13",
    "OnePlus 13R",
    "OnePlus 3",
    "OnePlus 3T",
    "OnePlus 5",
    "OnePlus 5T",
    "OnePlus 6",
    "OnePlus 6T",
    "OnePlus 6T McLaren",
    "OnePlus 7",
    "OnePlus 7 Pro",
    "OnePlus 7T",
    "Oneplus 7T Pro",
    "OnePlus 7T Pro McLaren Edition",
    "OnePlus 8",
    "OnePlus 8 Pro",
    "OnePlus 8T",
    "OnePlus 9 5G",
    "OnePlus 9 Pro 5G",
    "OnePlus 9R 5G",
    "OnePlus 9RT 5G",
    "OnePlus Nord",
    "OnePlus Nord 2 5G",
    "OnePlus Nord 2T 5G",
    "OnePlus Nord 3 5G",
    "OnePlus Nord 4",
    "OnePlus Nord CE 2 5G",
    "OnePlus Nord CE 2 Lite 5G",
    "OnePlus Nord CE 3 5G",
    "OnePlus Nord CE 3 Lite 5G",
    "OnePlus Nord CE 5G",
    "Oneplus Nord CE4 5G",
    "OnePlus Nord CE4 Lite 5G",
    "Oneplus Open",
    "OPPO A11K",
    "OPPO A12",
    "OPPO A15",
    "OPPO A15s",
    "OPPO A16",
    "OPPO A16e",
    "OPPO A16K",
    "OPPO A17",
    "OPPO A17K",
    "Oppo A18",
    "OPPO A1K",
    "OPPO A3 5G",
    "OPPO A3 Pro 5G",
    "OPPO A31",
    "OPPO A33 2020",
    "OPPO A38",
    "OPPO A3s",
    "OPPO A3x",
    "OPPO A3x 5G",
    "OPPO A5",
    "OPPO A5 2020",
    "OPPO A52",
    "OPPO A53",
    "OPPO A53s 5G",
    "OPPO A54",
    "OPPO A55",
    "OPPO A57",
    "OPPO A57 2022",
    "OPPO A58",
    "OPPO A59 5G",
    "OPPO A5s",
    "OPPO A7",
    "OPPO A71 2018",
    "OPPO A74 5G",
    "Oppo A76",
    "OPPO A77",
    "OPPO A77 2022",
    "OPPO A77s",
    "OPPO A78",
    "OPPO A78 5G",
    "OPPO A79 5G",
    "OPPO A83",
    "OPPO A9",
    "OPPO A9 2020",
    "OPPO A96",
    "OPPO F1 plus",
    "OPPO F11",
    "OPPO F11 Pro",
    "OPPO F11 Pro Avenger Edition",
    "OPPO F15",
    "OPPO F17",
    "OPPO F17 Pro",
    "OPPO F19",
    "Oppo F19 Pro",
    "OPPO F19 Pro Plus 5G",
    "OPPO F19s",
    "OPPO F1s",
    "OPPO F21 Pro",
    "OPPO F21 Pro 5G",
    "OPPO F21s Pro",
    "OPPO F21s Pro 5G",
    "OPPO F23 5G",
    "OPPO F25 Pro 5G",
    "OPPO F27 5G",
    "OPPO F27 Pro Plus 5G",
    "OPPO F29 5G",
    "OPPO F29 Pro 5G",
    "OPPO F3",
    "OPPO F3 Plus",
    "OPPO F5",
    "OPPO F5 Youth",
    "OPPO F7",
    "OPPO F9",
    "OPPO F9 Pro",
    "OPPO Find N2 Flip 5G",
    "OPPO Find N3 Flip 5G",
    "OPPO Find X",
    "OPPO Find X2",
    "OPPO Find X8 5G",
    "OPPO Find X8 Pro 5G",
    "OPPO K1",
    "OPPO K10",
    "OPPO K10 5G",
    "OPPO K12x 5G",
    "OPPO K3",
    "OPPO R11",
    "OPPO R17",
    "OPPO Reno",
    "OPPO Reno 10x Zoom",
    "OPPO Reno 2",
    "OPPO Reno 2Z",
    "OPPO Reno10 5G",
    "OPPO Reno10 Pro 5G",
    "OPPO Reno10 Pro Plus 5G",
    "OPPO Reno11 5G",
    "OPPO Reno11 Pro 5G",
    "OPPO Reno12 5G",
    "OPPO Reno12 Pro 5G",
    "OPPO Reno13 5G",
    "OPPO Reno13 Pro 5G",
    "OPPO Reno2 F",
    "OPPO Reno3 Pro",
    "OPPO Reno4 Pro",
    "OPPO Reno5 Pro 5G",
    "OPPO Reno6 5G",
    "OPPO Reno6 Pro 5G",
    "OPPO Reno7 5G",
    "OPPO Reno7 Pro 5G",
    "OPPO Reno8 5G",
    "OPPO Reno8 Pro 5G",
    "OPPO Reno8T 5G",
    "POCO C3",
    "POCO C31",
    "POCO C50",
    "POCO C51",
    "POCO C55",
    "POCO C61",
    "POCO C65",
    "POCO C75 5G",
    "POCO F1",
    "POCO F3 GT",
    "POCO F4 5G",
    "POCO F5 5G",
    "POCO F6 5G",
    "POCO M2",
    "POCO M2 Pro",
    "POCO M2 Reloaded",
    "POCO M3",
    "POCO M3 Pro 5G",
    "POCO M4 5G",
    "POCO M4 Pro",
    "POCO M4 Pro 5G",
    "POCO M5",
    "POCO M6 5G",
    "POCO M6 Plus 5G",
    "POCO M6 Pro 5G",
    "POCO M7 5G",
    "POCO M7 Pro 5G",
    "POCO X2",
    "POCO X3",
    "POCO X3 Pro",
    "POCO X4 Pro 5G",
    "POCO X5 5G",
    "POCO X5 Pro 5G",
    "POCO X5 GT 5G",
    "POCO X6 5G",
    "POCO X6 Neo 5G",
    "POCO X6 Pro 5G",
    "POCO X7 5G",
    "POCO X7 Pro 5G",
    "Realme 1",
    "Realme 10",
    "Realme 10 Pro 5G",
    "Realme 10 Pro Plus 5G",
    "Realme 11 5G",
    "Realme 11 5G Pro",
    "Realme 11 Pro 5G",
    "Realme 11 Pro Plus 5G",
    "Realme 11x 5G",
    "Realme 12 5G",
    "Realme 12 Plus 5G",
    "Realme 12 Pro 5G",
    "Realme 12 Pro Plus 5G",
    "Realme 12x 5G",
    "Realme 13 5G",
    "Realme 13 Plus 5G",
    "Realme 13 Pro 5G",
    "Realme 13 Pro Plus 5G",
    "Realme 14 Pro 5G",
    "Realme 14 Pro Lite 5G",
    "Realme 14 Pro Plus 5G",
    "Realme 14x 5G",
    "Realme 2",
    "Realme 2 Pro",
    "Realme 3",
    "Realme 3 Pro",
    "Realme 3i",
    "Realme 5",
    "Realme 5 Pro",
    "Realme 5s",
    "Realme 6",
    "Realme 6 Pro",
    "Realme 6i",
    "Realme 7",
    "Realme 7 Pro",
    "Realme 7i",
    "Realme 8",
    "Realme 8 5G",
    "Realme 8 Pro",
    "Realme 8i",
    "Realme 8s 5G",
    "Realme 9",
    "Realme 9 5G",
    "Realme 9 5G Speed Edition",
    "Realme 9 Pro 5G",
    "Realme 9 Pro Plus 5G",
    "Realme 9i",
    "Realme 9i 5G",
    "Realme C1",
    "Realme C1 2019",
    "Realme C11",
    "Realme C11 2021",
    "Realme C12",
    "Realme C15",
    "Realme C15 Qualcomm Edition",
    "Realme C2",
    "Realme C20",
    "Realme C21",
    "Realme C21Y",
    "Realme C25",
    "Realme C25s",
    "Realme C25Y",
    "Realme C3",
    "Realme C30",
    "Realme C30 5G",
    "Realme C30s",
    "Realme C31",
    "Realme C33",
    "Realme C33 2023",
    "Realme C35",
    "Realme C51",
    "Realme C53",
    "Realme C55",
    "Realme C61",
    "Realme C63",
    "Realme C63 5G",
    "Realme C63 5G",
    "Realme C65 5G",
    "Realme C67 5G",
    "Realme GT 2",
    "Realme GT 2 Pro",
    "Realme GT 5G",
    "Realme GT 6",
    "Realme GT 6T 5G",
    "Realme GT Master Edition",
    "Realme GT NEO 2",
    "Realme GT Neo 3",
    "Realme GT NEO 3 150W",
    "Realme GT NEO 3T",
    "Realme Narzo 10",
    "Realme Narzo 10A",
    "Realme Narzo 20",
    "Realme Narzo 20 Pro",
    "Realme Narzo 20A",
    "Realme Narzo 30",
    "Realme Narzo 30 5G",
    "Realme Narzo 30 Pro 5G",
    "Realme Narzo 30A",
    "Realme Narzo 50",
    "Realme Narzo 50 5G",
    "Realme Narzo 50 Pro 5G",
    "Realme Narzo 50A",
    "Realme Narzo 50A Prime",
    "Realme Narzo 50i",
    "Realme Narzo 50i Prime",
    "Realme Narzo 60 5G",
    "Realme Narzo 60 Pro 5G",
    "Realme Narzo 60X 5G",
    "Realme Narzo 70 5G",
    "Realme Narzo 70 Pro 5G",
    "Realme Narzo 70 Turbo 5G",
    "Realme Narzo 70x 5G",
    "Realme Narzo N53",
    "Realme Narzo N55",
    "Realme Narzo N61",
    "Realme Narzo N63",
    "Realme Narzo N65 5G",
    "Realme P1 5G",
    "Realme P1 Pro 5G",
    "Realme P1 Speed 5G",
    "Realme P2 Pro 5G",
    "Realme P3 5G",
    "Realme P3 Pro 5G",
    "Realme P3 Ultra 5G",
    "Realme P3X 5G",
    "Realme U1",
    "Realme X",
    "Realme X2",
    "Realme X2 Pro",
    "Realme X3",
    "Realme X3 SuperZoom",
    "Realme X50 Pro",
    "Realme X7",
    "Realme X7 Max 5G",
    "Realme X7 Pro",
    "Realme XT",
    "Samsung Galaxy A03",
    "Samsung Galaxy A03 Core",
    "Samsung Galaxy A03s",
    "Samsung Galaxy A04",
    "Samsung Galaxy A04s",
    "Samsung Galaxy A05",
    "Samsung Galaxy A05s",
    "Samsung Galaxy A06",
    "Samsung Galaxy A10",
    "Samsung Galaxy A10s",
    "Samsung Galaxy A12",
    "Samsung Galaxy A13",
    "Samsung Galaxy A14",
    "Samsung Galaxy A14 5G",
    "Samsung Galaxy A15 5G",
    "Samsung Galaxy A16 5G",
    "Samsung Galaxy A20",
    "Samsung Galaxy A20s",
    "Samsung Galaxy A21s",
    "Samsung Galaxy A22",
    "Samsung Galaxy A22 5G",
    "Samsung Galaxy A23",
    "Samsung Galaxy A23 5G",
    "Samsung Galaxy A25 5G",
    "Samsung Galaxy A30",
    "Samsung Galaxy A30s",
    "Samsung Galaxy A31",
    "Samsung Galaxy A32",
    "Samsung Galaxy A33 5G",
    "Samsung Galaxy A34 5G",
    "Samsung Galaxy A35 5G",
    "Samsung Galaxy A36 5G",
    "Samsung Galaxy A50",
    "Samsung Galaxy A50s",
    "Samsung Galaxy A51",
    "Samsung Galaxy A52",
    "Samsung Galaxy A52s 5G",
    "Samsung Galaxy A53 5G",
    "Samsung Galaxy A54 5G",
    "Samsung Galaxy A55 5G",
    "Samsung Galaxy A56 5G",
    "Samsung Galaxy A6 Plus",
    "Samsung Galaxy A7 2018",
    "Samsung Galaxy A70",
    "Samsung Galaxy A70s",
    "Samsung Galaxy A71",
    "Samsung Galaxy A72",
    "Samsung Galaxy A73 5G",
    "Samsung Galaxy A8 Plus",
    "Samsung Galaxy A8 Star",
    "Samsung Galaxy A80",
    "Samsung Galaxy A9 2018",
    "Samsung Galaxy A9 Pro",
    "Samsung Galaxy C7 Pro",
    "Samsung Galaxy C9 Pro",
    "Samsung Galaxy F02s",
    "Samsung Galaxy F04",
    "Samsung Galaxy F05",
    "Samsung Galaxy F06 5G",
    "Samsung Galaxy F12",
    "Samsung Galaxy F13",
    "Samsung Galaxy F14",
    "Samsung Galaxy F14 5G",
    "Samsung Galaxy F15 5G",
    "Samsung Galaxy F22",
    "Samsung Galaxy F23 5G",
    "Samsung Galaxy F34 5G",
    "Samsung Galaxy F41",
    "Samsung Galaxy F42 5G",
    "Samsung Galaxy F54 5G",
    "Samsung Galaxy F55 5G",
    "Samsung Galaxy F62",
    "Samsung Galaxy Fold",
    "Samsung Galaxy J6",
    "Samsung Galaxy J6 Plus",
    "Samsung Galaxy J7 Duo",
    "Samsung Galaxy J7 Max",
    "Samsung Galaxy J7 Nxt",
    "Samsung Galaxy J7 Pro",
    "Samsung Galaxy J8",
    "Samsung Galaxy M01",
    "Samsung Galaxy M01 Core",
    "Samsung Galaxy M01s",
    "Samsung Galaxy M02",
    "Samsung Galaxy M02s",
    "Samsung Galaxy M04",
    "Samsung Galaxy M05",
    "Samsung Galaxy M10s",
    "Samsung Galaxy M11",
    "Samsung Galaxy M12",
    "Samsung Galaxy M13",
    "Samsung Galaxy M13 5G",
    "Samsung Galaxy M14 4G",
    "Samsung Galaxy M14 5G",
    "Samsung Galaxy M15 5G",
    "Samsung Galaxy M20",
    "Samsung Galaxy M21",
    "Samsung Galaxy M21 2021 Edition",
    "Samsung Galaxy M30",
    "Samsung Galaxy M30s",
    "Samsung Galaxy M31",
    "Samsung Galaxy M31s",
    "Samsung Galaxy M32",
    "Samsung Galaxy M32 5G",
    "Samsung Galaxy M32 Prime Edition",
    "Samsung Galaxy M33 5G",
    "Samsung Galaxy M34 5G",
    "Samsung Galaxy M35 5G",
    "Samsung Galaxy M40",
    "Samsung Galaxy M42 5G",
    "Samsung Galaxy M51",
    "Samsung Galaxy M52 5G",
    "Samsung Galaxy M53 5G",
    "Samsung Galaxy M55 5G",
    "Samsung Galaxy M55s 5G",
    "Samsung Galaxy Note 10",
    "Samsung Galaxy Note 10 Lite",
    "Samsung Galaxy Note 10 Plus",
    "Samsung Galaxy Note 10 Plus 5G",
    "Samsung Galaxy Note 20",
    "Samsung Galaxy Note 20 Ultra 5G",
    "Samsung Galaxy Note 8",
    "Samsung Galaxy Note 9",
    "Samsung Galaxy On Max",
    "Samsung Galaxy On6",
    "Samsung Galaxy On7 Prime",
    "Samsung Galaxy On8 2018",
    "Samsung Galaxy S10",
    "Samsung Galaxy S10 Lite",
    "Samsung Galaxy S10 Plus",
    "Samsung Galaxy S10e",
    "Samsung Galaxy S20",
    "Samsung Galaxy S20 FE",
    "Samsung Galaxy S20 FE 5G",
    "Samsung Galaxy S20 Plus",
    "Samsung Galaxy S20 Ultra",
    "Samsung Galaxy S20 Ultra 5G",
    "Samsung Galaxy S21 5G",
    "Samsung Galaxy S21 FE 5G",
    "Samsung Galaxy S21 Plus 5G",
    "Samsung Galaxy S21 Ultra 5G",
    "Samsung Galaxy S22 5G",
    "Samsung Galaxy S22 Plus 5G",
    "Samsung Galaxy S22 Ultra 5G",
    "Samsung Galaxy S23 5G",
    "Samsung Galaxy S23 FE 5G",
    "Samsung Galaxy S23 Plus 5G",
    "Samsung Galaxy S23 Ultra 5G",
    "Samsung Galaxy S24 5G",
    "Samsung Galaxy S24 FE 5G",
    "Samsung Galaxy S24 Plus 5G",
    "Samsung Galaxy S24 Ultra 5G",
    "Samsung Galaxy S25 5G",
    "Samsung Galaxy S25 Plus 5G",
    "Samsung Galaxy S25 Ultra 5G",
    "Samsung Galaxy S8",
    "Samsung Galaxy S8 Plus",
    "Samsung Galaxy S9",
    "Samsung Galaxy S9 Plus",
    "Samsung Galaxy Z Flip",
    "Samsung Galaxy Z Flip3 5G",
    "Samsung Galaxy Z Flip4",
    "Samsung Galaxy Z Flip5",
    "Samsung Galaxy Z Flip6 5G",
    "Samsung Galaxy Z Fold2 5G",
    "Samsung Galaxy Z Fold3 5G",
    "Samsung Galaxy Z Fold4",
    "Samsung Galaxy Z Fold5",
    "Samsung Galaxy Z Fold6 5G",
    "Tecno Phantom V Fold 5G",
    "Tecno Phantom X",
    "Tecno Phantom X2 5G",
    "Tecno Phantom X2 Pro 5G",
    "Vivo NEX",
    "Vivo S1",
    "Vivo S1 Pro",
    "Vivo T1",
    "Vivo T1 5G",
    "Vivo T1 Pro 5G",
    "Vivo T1x",
    "Vivo T2 5G",
    "Vivo T2 Pro 5G",
    "Vivo T2x 5G",
    "Vivo T3 5G",
    "Vivo T3 Lite 5G",
    "Vivo T3 Pro 5G",
    "Vivo T3 Ultra",
    "Vivo T3x 5G",
    "Vivo U10",
    "Vivo U20",
    "Vivo V11",
    "Vivo V11 Pro",
    "Vivo V15",
    "Vivo V15 Pro",
    "Vivo V17",
    "Vivo V17 Pro",
    "Vivo V19",
    "Vivo V20",
    "Vivo V20 2021",
    "Vivo V20 Pro",
    "Vivo V20 SE",
    "Vivo V21 5G",
    "Vivo V21e 5G",
    "Vivo V23 5G",
    "Vivo V23 Pro",
    "Vivo V23e 5G",
    "Vivo V25 5G",
    "Vivo V25 Pro 5G",
    "Vivo V27",
    "Vivo V27 Pro",
    "Vivo V29",
    "Vivo V29 Pro",
    "Vivo V29e",
    "Vivo V30",
    "Vivo V30e",
    "Vivo V40",
    "Vivo V40 Pro",
    "Vivo V40e",
    "Vivo V5",
    "Vivo V50",
    "Vivo V50e",
    "Vivo V7",
    "Vivo V7 Plus",
    "Vivo V9",
    "Vivo V9 Pro",
    "Vivo V9 Youth",
    "Vivo X Fold 3 Pro",
    "Vivo X100",
    "Vivo X100 Pro",
    "Vivo X200",
    "Vivo X200 Pro",
    "Vivo X50",
    "Vivo X50 Pro",
    "Vivo X60",
    "Vivo X60 Pro",
    "Vivo X60 Pro Plus",
    "Vivo X70 Pro",
    "Vivo X70 Pro Plus",
    "Vivo X80",
    "Vivo X80 Pro",
    "Vivo X90",
    "Vivo X90 Pro",
    "Vivo Y01",
    "Vivo Y01a",
    "Vivo Y02",
    "Vivo Y02T",
    "Vivo Y100 5G",
    "Vivo Y100A 5G",
    "Vivo Y11 2019",
    "Vivo Y12",
    "Vivo Y12G",
    "Vivo Y12s",
    "Vivo Y15 2019",
    "Vivo Y15s 2021",
    "Vivo Y16",
    "Vivo Y17",
    "Vivo Y17s",
    "Vivo Y18",
    "Vivo Y18e",
    "Vivo Y18i",
    "Vivo Y18T",
    "Vivo Y19",
    "Vivo Y1s",
    "Vivo Y20",
    "Vivo Y200 5G",
    "Vivo Y200 Pro 5G",
    "Vivo Y200e 5G",
    "Vivo Y20A",
    "Vivo Y20G",
    "Vivo Y20i",
    "Vivo Y20T",
    "Vivo Y21 2021",
    "Vivo Y21a",
    "Vivo Y21e",
    "Vivo Y21G",
    "Vivo Y21T",
    "Vivo Y22 2022",
    "Vivo Y27",
    "Vivo Y28 5G",
    "Vivo Y28e 5G",
    "Vivo Y28s 5G",
    "Vivo Y29 5G",
    "Vivo Y30",
    "Vivo Y300 5G",
    "Vivo Y300 Plus 5G",
    "Vivo Y31 2021",
    "Vivo Y33s",
    "Vivo Y33T",
    "Vivo Y35",
    "Vivo Y36",
    "Vivo Y3s 2021",
    "Vivo Y50",
    "Vivo Y51 2020",
    "Vivo Y51A",
    "Vivo Y53s",
    "Vivo Y55s",
    "Vivo Y56 5G",
    "Vivo Y58 5G",
    "Vivo Y66",
    "Vivo Y69",
    "Vivo Y71",
    "Vivo Y71i",
    "Vivo Y72 5G",
    "Vivo Y73",
    "Vivo Y75",
    "Vivo Y75 5G",
    "Vivo Y81",
    "Vivo Y81i",
    "Vivo Y83",
    "Vivo Y83 Pro",
    "Vivo Y90",
    "Vivo Y91",
    "Vivo Y91i",
    "Vivo Y93",
    "Vivo Y95",
    "Vivo Z1 Pro",
    "Vivo Z1x",
    "Xiaomi 11 Lite NE 5G",
    "Xiaomi 11i 5G",
    "Xiaomi 11i Hypercharge 5G",
    "Xiaomi 11T Pro 5G",
    "Xiaomi 12 Pro 5G",
    "Xiaomi 13 Pro 5G",
    "Xiaomi 14",
    "Xiaomi 14 CIVI",
    "Xiaomi 14 Ultra",
    "Xiaomi Black Shark 2",
    "Xiaomi Mi 10",
    "Xiaomi Mi 10i",
    "Xiaomi Mi 10T",
    "Xiaomi Mi 10T Pro",
    "Xiaomi Mi 11 Lite",
    "Xiaomi Mi 11 Ultra",
    "Xiaomi Mi 11X",
    "Xiaomi Mi 11X Pro",
    "Xiaomi Mi A2",
    "Xiaomi Mi A3",
    "Xiaomi Mi Max 2",
    "Xiaomi Mi Mix 2",
    "Xiaomi Redmi 10",
    "Xiaomi Redmi 10 Power",
    "Xiaomi Redmi 10 Prime",
    "Xiaomi Redmi 10 Prime 2022",
    "Xiaomi Redmi 10A",
    "Xiaomi Redmi 11 Prime",
    "Xiaomi Redmi 11 Prime 5G",
    "Xiaomi Redmi 12",
    "Xiaomi Redmi 12 5G",
    "Xiaomi Redmi 12C",
    "Xiaomi Redmi 13 5G",
    "Xiaomi Redmi 13C",
    "Xiaomi Redmi 13C 5G",
    "Xiaomi Redmi 14C 5G",
    "Xiaomi Redmi 5",
    "Xiaomi Redmi 5A",
    "Xiaomi Redmi 6",
    "Xiaomi Redmi 6 pro",
    "Xiaomi Redmi 6A",
    "Xiaomi Redmi 7",
    "Xiaomi Redmi 7A",
    "Xiaomi Redmi 8",
    "Xiaomi Redmi 8A",
    "Xiaomi Redmi 8A Dual",
    "Xiaomi Redmi 9",
    "Xiaomi Redmi 9 Activ",
    "Xiaomi Redmi 9 Power",
    "Xiaomi Redmi 9 Prime",
    "Xiaomi Redmi 9A",
    "Xiaomi Redmi 9i",
    "Xiaomi Redmi A1",
    "Xiaomi Redmi A1 Plus",
    "Xiaomi Redmi A2",
    "Xiaomi Redmi A2 Plus",
    "Xiaomi Redmi A3",
    "Xiaomi Redmi A3x",
    "Xiaomi Redmi Go",
    "Xiaomi Redmi K20",
    "Xiaomi Redmi K20 Pro",
    "Xiaomi Redmi K50i 5G",
    "Xiaomi Redmi Note 10",
    "Xiaomi Redmi Note 10 Lite",
    "Xiaomi Redmi Note 10 Pro",
    "Xiaomi Redmi Note 10 Pro Max",
    "Xiaomi Redmi Note 10s",
    "Xiaomi Redmi Note 10T 5G",
    "Xiaomi Redmi Note 11",
    "Xiaomi Redmi Note 11 Pro",
    "Xiaomi Redmi Note 11 Pro Plus 5G",
    "Xiaomi Redmi Note 11 SE",
    "Xiaomi Redmi Note 11S",
    "Xiaomi Redmi Note 11T 5G",
    "Xiaomi Redmi Note 12",
    "Xiaomi Redmi Note 12 5G",
    "Xiaomi Redmi Note 12 Pro 5G",
    "Xiaomi Redmi Note 12 Pro Plus 5G",
    "Xiaomi Redmi Note 13 5G",
    "Xiaomi Redmi Note 13 Pro 5G",
    "Xiaomi Redmi Note 13 Pro Plus 5G",
    "Xiaomi Redmi Note 14 5G",
    "Xiaomi Redmi Note 14 Pro 5G",
    "Xiaomi Redmi Note 14 Pro Plus 5G",
    "Xiaomi Redmi Note 5",
    "Xiaomi Redmi Note 5 Pro",
    "Xiaomi Redmi Note 6 Pro",
    "Xiaomi Redmi Note 7",
    "Xiaomi Redmi Note 7 Pro",
    "Xiaomi Redmi Note 7S",
    "Xiaomi Redmi Note 8",
    "Xiaomi Redmi Note 8 Pro",
    "Xiaomi Redmi Note 9",
    "Xiaomi Redmi Note 9 Pro",
    "Xiaomi Redmi Note 9 Pro Max",
    "Xiaomi Redmi Y1",
    "Xiaomi Redmi Y1 Lite",
    "Xiaomi Redmi Y2",
    "Xiaomi Redmi Y3",
]


export default mobileDevices;